language: java

sudo: required

services:
  - docker

env:
  - AMBARI_RELEASE: 2.5.2
  - AMBARI_RELEASE: 2.6.1

if: tag IS present

script:
  - make build

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  - provider: script
    script: make deploy
    on:
      tags: true
