language: java

sudo: required

services:
  - docker

cache:
  directories:
  - $HOME/.m2

script:
  - timeout 2700 make build || touch BUILD_TIMED_OUT

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  - provider: script
    script: 'if [ ! -f BUILD_TIMED_OUT ]; then make deploy; fi'
    on:
      all_branches: true
